version: '2.2'
# volumes:
#    geoserver-data: /Users/limingzhi/docker_data/geoserver/data_dir
#    geo-db-data: /Users/limingzhi/docker_data/geoserver/postgis_db
 
services:
   db:
      image: kartoza/postgis:14-3.1
      # volumes:
        #  - /home/limingzhi/docker_data/geoserver/pg_db:/var/lib/postgresql
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=db_gis
        - POSTGRES_USER=postgres
        - POSTGRES_PASS=postgres
        - ALLOW_IP_RANGE=0.0.0.0/0
      restart: on-failure
      healthcheck:
        test: "exit 0"
 
   geoserver:
      image: kartoza/geoserver:2.23.2
      volumes:
        - /home/limingzhi/docker_data/geoserver/geotmp:/data_dir
        - /home/limingzhi/docker_data/geoserver/data_dir:/opt/geoserver/data_dir/data
        - /home/limingzhi/docker_data/geoserver/cache_dir:/opt/geoserver/data_dir/gwc
      ports:
        - 8088:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
        - GEOSERVER_ADMIN_USER=dxy123
        - GEOSERVER_ADMIN_PASSWORD=dxy
        
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8088/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3